bazaar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),

    # Django admin
    path('admin/', admin.site.urls),

    # User Management
    path('user/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

    #Products
    path('product/', include('products.urls')),
    path('category/', include('products.category_urls')),
    path('unmoderated-products/', views.AllProductsView.as_view(), name='view_all_products'),
    path('moderate/', views.UnmoderatedProductsView.as_view(), name='moderate')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add', views.addProduct, name='add_product'),
    path('<my_hash>/<slug:slug>/', views.viewProduct,
    name='view_product'),
    path('<my_hash>/<slug:slug>/modify', views.modifyProduct,
    name='modify_product'),
]

users/urls.py
from django.urls import path
from . import views
from django.shortcuts import reverse

urlpatterns = [
    path('<my_hash>/<slug:slug>/', views.viewUser, name='view_user')
]

products/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from mptt.models import MPTTModel, TreeForeignKey
from django.shortcuts import reverse
import hash_info

# Create your models here.
class Category(MPTTModel):
    name = models.CharField("Category name", max_length=50)
    description = models.TextField(blank=True, null=True)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='child_category_name',
    )
    my_hash = models.TextField(
        blank=True,
        null=True,
    )
    slug = models.TextField(
        blank=True,
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['id']

    def get_absolute_url(self):
        return reverse("view_category", kwargs={
            "slug": self.slug,
            "my_hash": self.my_hash,
        })

class Product(models.Model):
    name = models.TextField("Product name")
    description = models.TextField("Product description")
    time_added = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(
        "Product approved by moderators",
        default=False,
        blank=True,
    )
    mod_review = models.TextField(
        "Review sent by moderator",
        null=True,
        blank=True,
    )
    reviewed_by_mod = models.BooleanField(
        "Was product reviewed by Moderator",
        default=False,
        blank=True
    )
    approved_by = models.ForeignKey(
        'users.CustomUser',
        models.SET_NULL,
        null=True,
        blank=True,
        related_name='products_approved',
        limit_choices_to={'groups__name': 'Moderators'},
    )
    added_by = models.ForeignKey(
        'users.CustomUser',
        models.CASCADE,
        null=True,
        blank=True,
        related_name='products_added'
    )
    category = models.ForeignKey(
        'Category',
        models.SET_NULL,
        null=True,
        related_name='products'
    )
    price = models.DecimalField(
        "Price of the product (in INR)",
        max_digits=8, #Max amount 9,99,999.99 (more than sufficient)
        decimal_places=2,
    )   
    negotiable = models.BooleanField(default=False)
    my_hash = models.TextField(
        blank=True,
        null=True,
    )
    slug = models.TextField(
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("view_product", kwargs={
            "slug": self.slug,
            "my_hash": self.my_hash,
        })

    def get_modify_url(self):
        return reverse("modify_product", kwargs={
            'slug': self.slug,
            'my_hash': self.my_hash,
        })

class Transaction(models.Model):
    seller = models.ForeignKey(
        'users.CustomUser',
        models.SET_NULL,
        related_name='products_sold',
        null=True,
    )
    buyer = models.ForeignKey(
        'users.CustomUser',
        models.SET_NULL,
        related_name='products_bought',
        null=True,
    )
    product = models.ForeignKey(
        'Product',
        models.PROTECT
    )
    time = models.DateTimeField(
        'Time of transaction',
        auto_now_add=True
    )

#Helper class to store images
class Images(models.Model):
    product = models.ForeignKey(
        Product,
        models.CASCADE,
        default=None,
        related_name='product_image',
    )

    image = models.ImageField(
        upload_to='uploads/',
        verbose_name='Image',
    )

products/forms.py
from django.forms import ModelForm, ImageField, ClearableFileInput
from .models import Category, Product, Images
from mptt.forms import TreeNodeChoiceField
from django import forms

class ProductForm(ModelForm):
    category = TreeNodeChoiceField(
        queryset=Category.objects.all()
    )

    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'price',
            'negotiable',
        ]

class ImageForm(ModelForm):
    image = ImageField(label='Image', widget=ClearableFileInput)    
    class Meta:
        model = Images
        fields = ('image', )

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'parent',
            'name',
            'description'
        ]

class ModReviewForm(forms.Form):
    approve = forms.BooleanField(label="Approve?", required=False)
    comments = forms.CharField(required=False)

products/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from .models import Product, Category, Images
from .forms import ProductForm, CategoryForm, ImageForm, ModReviewForm

from django.utils.text import slugify
from users.templatetags.user_in_group import is_moderator

import hash_info

@login_required
def addProduct(request):
    ImageFormSet = modelformset_factory(
        Images,
        form=ImageForm,
        extra=5
    )

    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        formset = ImageFormSet(
            request.POST,
            request.FILES,
            queryset=Images.objects.none(),
        )
        if product_form.is_valid() and formset.is_valid():
            product = product_form.save(commit=False)
            product.added_by = request.user
            product.category = product_form.cleaned_data['category']
            product.slug = slugify(product_form.cleaned_data['name'])
            product.save()
            product.my_hash = hash_info.PRODUCT.encode(product.id)
            product.save()

            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    photo = Images(product=product, image=image)
                    photo.save()

            return redirect(product)
    else:
        product_form = ProductForm()
        formset = ImageFormSet(queryset=Images.objects.none())

    return render(
        request,
        'products/addproduct.html',
        {
            'product_form': product_form,
            'formset': formset,
        }
    )

def redirecter(my_hash, slug, hasher, my_class):
    object_ids = hasher.decode(my_hash)

    if len(object_ids) != 1:
        raise Http404("Hash is wrong")
    object_id = object_ids[0]

    try:
        obj = my_class.objects.get(pk=object_id)
    except my_class.DoesNotExist:
        raise Http404("id corresponding to hash doesn't exist")
    
    if slug != obj.slug:
        return obj, True
    return obj, False

class viewProductClass(DetailView):
    model = Product
    template_name = 'products/viewproduct.html'

    def get_object(self):
        product = self.kwargs.get('product')
        if product:
            return product
        
        return super().get_object(self)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_qset'] = self.kwargs.get('category_qset')
        context['form'] = self.kwargs.get('form')
        return context
    
def viewProduct(request, my_hash, slug):
    product, need_to_redirect = redirecter(
        my_hash,
        slug,
        hash_info.PRODUCT,
        Product
    )

    if request.method == 'POST' and request.user.groups.filter(name='Moderators').exists():
        form = ModReviewForm(request.POST)
        if form.is_valid():
            product.approved = form.cleaned_data['approve']
            product.mod_review = form.cleaned_data['comments']
            product.reviewed_by_mod = True
            if form.cleaned_data['approve']:
                product.approved_by = request.user
            product.save()
            return redirect(product)
    elif request.method == 'GET':
        form = ModReviewForm()

    if need_to_redirect:
        return redirect(product, permanent=True)

    return viewProductClass.as_view()(request, product=product,
    category_qset=product.category.get_ancestors(), form=form)

class ProductsByCategoryView(ListView):
    template_name = 'products/view_products_by_category.html'
    queryset = Product.objects.all()
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_qset'] = self.category.get_ancestors(include_self=True)
        return context

    def get_queryset(self):
        category, need_to_redirect = redirecter(
            self.kwargs['my_hash'],
            self.kwargs['slug'],
            hash_info.CATEGORY,
            Category
        )

        if need_to_redirect:
            return redirect(category, permanent=True)

        category_queryset = category.get_descendants(include_self=True)
        self.queryset = Product.objects.all().filter(
            category__in=category_queryset
        ).filter(approved=True)
        self.category = category
        print('yay')
        return self.queryset

class UnmoderatedProductsByCategoryView(ProductsByCategoryView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['unmoderated'] = True
        return context

    def get_queryset(self):
        qset = super().get_queryset()
        qset2 = Product.objects.all().filter(reviewed_by_mod=False)
        qset = (qset | qset2).distinct()
        return qset

@login_required
def modifyProduct(request, my_hash, slug):
    product, need_to_redirect = redirecter(
        my_hash,
        slug,
        hash_info.PRODUCT,
        Product
    )

    if need_to_redirect:
        url = product.get_absolute_url() + 'modify/'
        return redirect(url, permanent=True)
    
    if(product.added_by != request.user and not is_moderator(request.user)):
        raise PermissionDenied
    
    ImageFormSet = modelformset_factory(
        Images,
        form=ImageForm,
        extra=5,
        max_num=5,
    )

    if request.method == 'POST':
        product_form = ProductForm(request.POST, instance=product)
        formset = ImageFormSet(
            request.POST,
            request.FILES,
        )
        if product_form.is_valid() and formset.is_valid():
            product = product_form.save(commit=False)
            product.added_by = request.user
            product.category = product_form.cleaned_data['category']
            product.slug = slugify(product_form.cleaned_data['name'])
            product.save()
            product.my_hash = hash_info.PRODUCT.encode(product.id)
            product.save()

            Images.objects.all().filter(product=product).delete()
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    photo = Images(product=product, image=image)
                    photo.save()

            return redirect(product)
    else:
        product_form = ProductForm(instance=product)
        product_form.fields['category'].initial = [product.category.id]
        formset = ImageFormSet(queryset=Images.objects.filter(product=product))

    return render(
        request,
        'products/addproduct.html',
        {
            'product_form': product_form,
            'formset': formset,
        }
    )

def ViewAllCategories(request):
    return render(request, "products/view_all_categories.html", {
        'categories': Category.objects.all()
})

products/templates/products/addproduct.html
{% include 'navbar.html' %}

<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ product_form }}

        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}
        {% endfor %}
    </table>
    <input type="submit" value="Save product!"/>
</form>

products/templates/products/category_breadcrumbs.html
{% for ancestor in category_qset %}
    <a href="{% url 'view_category' ancestor.my_hash ancestor.slug %}">
        {{ ancestor.name }} 
    </a>
    > 
{% endfor %}

{% if current_category %}
    {% with current_category as c %}
        <a href="{% url 'view_category' c.my_hash c.slug %}">
                {{c.name}}
            </a>
    {% endwith %}
{% endif %}

products/templates/products/product_card.html
<a href="{{ product.get_absolute_url }}"> {{ product.name }} </a>
    : {{ product.description }} <br>
    {% if show_userinfo %}
        Sold by: <a href="{{ product.added_by.get_absolute_url }}">
            {{ product.added_by.get_full_name }}
        </a>
    {% endif %}

products/templates/products/view_all_categories.html
{% include 'navbar.html' %}

VIew our catalog by categories:
{% load mptt_tags %}
<ul>
    {% recursetree categories %}
        <li>
            <a href="{{ node.get_absolute_url }}">
                {{ node.name }}
            </a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

products/templates/products/view_all_products.html
<ul>
{% for product in product_list %}
    <li>
        Category: 
        {% include 'products/category_breadcrumbs.html' with category_qset=product.category.get_ancestors current_category=product.category %}
        <br><br>
        {% include 'products/product_card.html' with show_userinfo=True %}
    </li>
    <br>
{% endfor %}
</ul>

products/templates/products/view_products_by_category.html
{% include 'navbar.html' %}

<b><big> View products by category </big></b> <br><br>

{% if not unmoderated %}
    <a href="{{ request.path }}/unmoderated">
        Click here
    </a> to view unmoderated products of this category
{% else %}
    <b style="color:red">
        NOTE: This section contains products that have not been reviewed
        by the moderation. Proceed at own risk.
    </b>
{% endif %}

<br><br>

Category:
{% include 'products/category_breadcrumbs.html' %}

{% include 'products/view_all_products.html' %}

products/templates/products/viewproduct.html
{% load user_in_group %}

{% include 'navbar.html' %}

{% if not product.approved and not product.reviewed_by_mod %}
    {% if not request.user|is_moderator %}
        <b style="color:red">
            Note: This product has not yet been approved by any moderator.<br>
            We are not responsible for the contents of this page.
        </b>
    {% else %}
        <b style="color:red">
            Unmoderated product. Please review it and take necessary actions.
        </b>
    {% endif %}
    <br><br>
{% endif %}

{% if product.reviewed_by_mod and not product.approved %}
    Product has been viewed by moderation and has not been approved.<br>
    {% if request.user == product.added_by %}
        Moderation commented: <br>
        {{ product.mod_review }} <br>
    {% endif %}
{% endif %}

{% if request.user == product.added_by %}
    <a href="{{ product.get_modify_url }}">
        Edit product details
    </a>
    <br><br>
{% endif %}

{% if not product.reviewed_by_mod or product.approved %}

<b> Category: </b>
{% include 'products/category_breadcrumbs.html' with current_category=object.category %}

<h1> Product name: {{ object.name }} </h1>

<h2>
    Product description:
</h2>
<p><b>
    {{ object.description }}
</b></p>

Buy now for Rs. {{ object.price }}
{% if object.negotiable %}(Negotiable){% endif %}

<br>

Seller: <a href="{% url 'view_user' object.added_by.my_hash object.added_by.slug %}">
    {{ object.added_by.get_full_name }} 
</a> <br>

<b> Product Images: </b>
<ul style="list-style-type:none">
{% for image in product.product_image.all %}
    <li><img src = "{{ image.image.url }}" /></li>
{% endfor %}
</ul>

<br>

{% if request.user.is_authenticated %}
    Contact the seller at {{ object.added_by.phone_number }} or 
    {{ object.added_by.email }} to buy this product.
{% else %}
    Please <a href = "{% url 'account_login' %}?next={{ request.path }}"> login </a>
    to buy the product.
{% endif %}

{% if request.user|is_moderator and not product.approved and not product.reviewed_by_mod %}
<form action="{{ request.path }}" method="post">
    <br><br>
    <b style="color:red">
        {% csrf_token %}
        {{ form }}
    </b>
    <input type="submit" value="Submit">
</form>
{% endif %}

{% endif %}